---
services:
  main:
    image: docker.io/dmotte/portfwd-server-rootless:latest
    build: build
    restart: always
    network_mode: bridge
    ports: ["2222:2222"]
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ssh-host-keys:/ssh-host-keys
      - ./ssh-client-keys:/ssh-client-keys
    environment:
      PERMIT_LISTEN: 127.0.0.1:8001 127.0.0.1:8002 10.0.2.2:8003

volumes:
  ssh-host-keys: {}
